### ISSUE TITLE
无法解密报错

### ISSUE THREAD

**Issue by smallfawn** [0verp0wer/pyobfuscate.com-deobfuscator#2]
content_deobfuscated = decrypt_string(eval(value_str))
TypeError: eval() arg 1 must be a string, bytes or code object
我用的是https://pyobfuscate.com/pyd 加密方法

**Comment by 0verp0wer** [comment]
> ```
> content_deobfuscated = decrypt_string(eval(value_str))
> ```
> 
> TypeError: eval() arg 1 must be a string, bytes or code object 我用的是https://pyobfuscate.com/pyd 加密方法

hi, please send the file here or on discord and I will check it

**Comment by 0verp0wer** [comment]
> ```
> content_deobfuscated = decrypt_string(eval(value_str))
> ```
> 
> TypeError: eval() arg 1 must be a string, bytes or code object 我用的是https://pyobfuscate.com/pyd 加密方法

I Will close this issue because you have not sent the file, if you Need other help open a new ticket
